# In _config.yml
title: Banana Collector Report
author: Joerg Wangemann
execute:
  execute_notebooks: off

repository:
  url: https://github.com/joewa/ml-agents-banana-collector
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image
